from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Iterable


PROJECT_DIRS = (
    "source-docs",
    "research",
    "requirements",
    "diagrams",
    "deliverables",
    "workspace",
)

WORKSPACE_FILES = {
    "decisions.yaml": "decisions: []\n",
    "assumptions.yaml": "assumptions: []\n",
    "open-questions.yaml": "questions: []\n",
    "glossary.yaml": "terms: []\n",
    "context-summary.md": "# Project Context Summary\n\nAdd the current project context here.\n",
}


@dataclass(frozen=True)
class ProjectInfo:
    name: str
    slug: str
    description: str
    created: str
    workspace_path: Path
    knowledge_path: Path


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.strip().lower()).strip("-")
    if not slug:
        raise ValueError("Project name must contain at least one letter or number")
    return slug


def find_repo_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    for candidate in (current, *current.parents):
        if (candidate / "agents").is_dir() and (candidate / "knowledge").is_dir():
            return candidate
    raise FileNotFoundError(
        "Pulse repository root not found. Run this command inside pulse-agent-kit."
    )


def _quote_yaml(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _project_yaml(info: ProjectInfo) -> str:
    return (
        "schema_version: 1\n"
        f"name: {_quote_yaml(info.name)}\n"
        f"slug: {_quote_yaml(info.slug)}\n"
        f"description: {_quote_yaml(info.description)}\n"
        f"created: {_quote_yaml(info.created)}\n"
        "status: active\n"
        f"knowledge_path: {_quote_yaml(info.knowledge_path.as_posix())}\n"
        "agents:\n"
        "  - researcher\n"
        "  - itba\n"
    )


def create_project(
    root: Path,
    name: str,
    slug: str | None = None,
    description: str = "",
) -> ProjectInfo:
    project_slug = slugify(slug or name)
    workspace_rel = Path("projects") / project_slug
    knowledge_rel = Path("knowledge") / "projects" / project_slug
    workspace = root / workspace_rel
    knowledge = root / knowledge_rel

    if workspace.exists() or knowledge.exists():
        raise FileExistsError(f"Project '{project_slug}' already exists")

    info = ProjectInfo(
        name=name.strip(),
        slug=project_slug,
        description=description.strip(),
        created=date.today().isoformat(),
        workspace_path=workspace_rel,
        knowledge_path=knowledge_rel,
    )

    try:
        for directory in PROJECT_DIRS:
            (workspace / directory).mkdir(parents=True, exist_ok=False)
        for filename, content in WORKSPACE_FILES.items():
            (workspace / "workspace" / filename).write_text(content, encoding="utf-8")

        (workspace / "project.yaml").write_text(_project_yaml(info), encoding="utf-8")
        (workspace / "README.md").write_text(
            f"# {info.name}\n\n"
            "Project workspace generated by Pulse Agent Kit.\n\n"
            "- Put original files in `source-docs/`.\n"
            "- Store research reports in `research/`.\n"
            "- Store requirements in `requirements/`.\n"
            "- Store diagrams in `diagrams/`.\n"
            "- Store final outputs in `deliverables/`.\n"
            "- Track decisions and open questions in `workspace/`.\n",
            encoding="utf-8",
        )

        (knowledge / "pages").mkdir(parents=True, exist_ok=False)
        (knowledge / ".rag").mkdir(parents=True, exist_ok=False)
        (knowledge / "project.yaml").write_text(_project_yaml(info), encoding="utf-8")
        (knowledge / "pages" / "README.md").write_text(
            f"# {info.name} knowledge\n\n"
            "Add normalized Markdown knowledge pages here, then build the RAG index.\n",
            encoding="utf-8",
        )
        (knowledge / ".rag" / "index.json").write_text("[]\n", encoding="utf-8")
        (knowledge / ".rag" / "vectors.json").write_text("[]\n", encoding="utf-8")
    except Exception:
        _remove_tree(workspace)
        _remove_tree(knowledge)
        raise

    return info


def _remove_tree(path: Path) -> None:
    if not path.exists():
        return
    for child in sorted(path.rglob("*"), reverse=True):
        if child.is_file() or child.is_symlink():
            child.unlink()
        elif child.is_dir():
            child.rmdir()
    path.rmdir()


def list_projects(root: Path) -> list[ProjectInfo]:
    projects_root = root / "projects"
    if not projects_root.exists():
        return []
    result: list[ProjectInfo] = []
    for config in sorted(projects_root.glob("*/project.yaml")):
        result.append(read_project(root, config.parent.name))
    return result


def read_project(root: Path, identifier: str) -> ProjectInfo:
    slug = slugify(identifier)
    config = root / "projects" / slug / "project.yaml"
    if not config.exists():
        raise FileNotFoundError(f"Project '{identifier}' was not found")
    values = _read_simple_yaml(config.read_text(encoding="utf-8"))
    return ProjectInfo(
        name=values.get("name", slug),
        slug=values.get("slug", slug),
        description=values.get("description", ""),
        created=values.get("created", ""),
        workspace_path=Path("projects") / slug,
        knowledge_path=Path(values.get("knowledge_path", f"knowledge/projects/{slug}")),
    )


def _read_simple_yaml(content: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in content.splitlines():
        if not raw_line or raw_line[0].isspace() or ":" not in raw_line:
            continue
        key, value = raw_line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        values[key.strip()] = value
    return values


def missing_project_paths(root: Path, info: ProjectInfo) -> Iterable[Path]:
    required = [
        root / info.workspace_path / "project.yaml",
        root / info.workspace_path / "workspace" / "decisions.yaml",
        root / info.workspace_path / "workspace" / "assumptions.yaml",
        root / info.workspace_path / "workspace" / "open-questions.yaml",
        root / info.workspace_path / "workspace" / "glossary.yaml",
        root / info.knowledge_path / "pages",
        root / info.knowledge_path / ".rag",
    ]
    return (path for path in required if not path.exists())
